Repository jijun0129/sphereAXmultimodal, pull requests merged in 2024-11, with the labels that each got.

#30 Feat: BE 북마크 관련 기능 구현
  Back/app/controllers/bookmark.controller.js
  Back/app/controllers/user.controller.js
  Back/app/middlewares/auth.middleware.js
  Back/app/models/Bookmark.js
  Back/app/routes/user.api.routes.js
  Back/config/express_config.js
  Back/config/mongoose_config.js
  Back/config/routes_config.js
  Back/package-lock.json
Labels: Backend, Feat

#31 feat(FE): 검색기록 페이지 기본 구성 완료
  Front/src/components/component/LogData.vue
  Front/src/pages/log.vue
  Front/src/pages/main.vue
  Front/src/store/index.js
Labels: Frontend, Feat

#34 feat(FE): 북마크 페이지 기본 구성 완료
  Front/src/components/component/ImageData.vue
  Front/src/pages/bookmark.vue
  Front/src/pages/result.vue
  Front/src/store/index.js
Labels: Frontend, Feat

#39 FE 상세보기 기능 구현
  Front/src/components/component/ImageData.vue
  Front/src/components/component/ImageModal.vue
  Front/src/components/component/LogModal.vue
  Front/src/pages/bookmark.vue
  Front/src/pages/log.vue
  Front/src/store/index.js
Labels: Frontend, Feat

#41 FE 전반적인 디자인 수정
  Front/src/assets/dummy/2.jpg
  Front/src/components/component/ImageData.vue
  Front/src/components/component/ImageModal.vue
  Front/src/components/component/LogData.vue
  Front/src/components/component/LogModal.vue
  Front/src/pages/bookmark.vue
  Front/src/pages/login.vue
  Front/src/pages/main.vue
  Front/src/pages/result.vue
  Front/src/pages/signup.vue
  Front/src/store/index.js
Labels: Frontend, Feat

#43 feat(FE): 회의 후 변경 부분 반영
  Front/src/composables/useAxios.js
  Front/src/composables/useSocket.js
  Front/src/main.js
  Front/src/pages/login.vue
  Front/src/plugins/axios.js
  Front/src/plugins/socket.js
  Front/src/store/socket.js
Labels: Frontend, Feat

#45 Feat : 검색 기록 관련 기능 구현
  Back/app/controllers/bookmark.controller.js
  Back/app/controllers/search.controller.js
  Back/app/controllers/searchHistory.controller.js
  Back/app/controllers/user.controller.js
  Back/app/middlewares/auth.middleware.js
  Back/app/routes/user.api.routes.js
  Back/server.js
Labels: Backend, Feat

#46 feat(FE): 컴포넌트에는 컴포넌트만 있게 파일 구조 변경
  Front/src/UI/BaseButton.vue
  Front/src/components/ImageData.vue
  Front/src/components/ImageModal.vue
  Front/src/components/LogData.vue
  Front/src/components/LogModal.vue
  Front/src/components/UI/BaseCard.vue
  Front/src/layout/TheFooter.vue
  Front/src/layout/TheHeader.vue
  Front/src/main.js
  Front/src/pages/bookmark.vue
  Front/src/pages/log.vue
  Front/src/pages/main.vue
  Front/src/pages/result.vue
  package-lock.json
  package.json
Labels: Frontend, Feat

#51 Fix: BE sokcet io 관련 연결 메커니즘 수정
  Back/app/controllers/socketio.controller.js
  Back/config/socketio.js
Labels: Backend, Fix
