Repository jijun0129/sphereAXmultimodal, pull requests merged in 2024-10, with the labels that each got.

#4 Establish: 초기 베이스 코드 세팅
  Back/app/controllers/socketio.controller.js
  Back/app/controllers/user.controller.js
  Back/app/models/UserInfo.js
  Back/app/models/UserLogs.js
  Back/app/routes/user.api.routes.js
  Back/config/env/development.js
  Back/config/env/production.js
  Back/config/express_config.js
  Back/config/mongoose_config.js
  Back/config/node_config.js
  Back/config/passport/strategies/user.js
  Back/config/passport/user_passport.js
  Back/config/routes_config.js
  Back/config/socketio.js
  Back/package-lock.json
  Back/package.json
  Back/server.js
Labels: Backend

#6 Docs: README 추가
  README.md
Labels: Docs

#14 Docs: README.md 파일 스코프 관련 수정 및 내용 추가
  README.md
Labels: Docs

#15 Establish(FE): pinia 초기 세팅 완료
  Front/package-lock.json
  Front/package.json
  Front/src/main.js
  Front/src/store/index.js
Labels: Frontend

#17 Feat(FE): 웹페이지 헤더 구현
  Front/src/components/UI/BaseButton.vue
  Front/src/components/layout/TheHeader.vue
  Front/src/main.js
  Front/src/pages/bookmark.vue
  Front/src/pages/log.vue
  Front/src/pages/login.vue
  Front/src/pages/main.vue
  Front/src/router/index.js
Labels: Frontend, Feat

#20 FE 메인페이지 구현
  Front/src/components/UI/BaseButton.vue
  Front/src/components/UI/BaseCard.vue
  Front/src/main.js
  Front/src/pages/bookmark.vue
  Front/src/pages/log.vue
  Front/src/pages/login.vue
  Front/src/pages/main.vue
  Front/src/pages/result.vue
  Front/src/router/index.js
  Front/src/store/index.js
  Front/src/style.css
Labels: Frontend, Feat

#22 Feat(FE): 결과페이지 구현 및 북마크 pinia에 저장
  Front/src/assets/dummy/1.jpg
  Front/src/pages/result.vue
  Front/src/store/index.js
Labels: Frontend, Feat
