Repository jijun0129/sphereAXmultimodal, pull requests merged in 2024-12, with the labels that each got.

#52 Fix:BE 이미지 get 요청에 대한 CORS 에러 수정
  Back/config/express_config.js
Labels: Backend, Fix

#54 Fix:BE 검색 기록 상세 조회 시 북마크 여부 확인 기능 추가
  Back/app/controllers/searchHistory.controller.js
Labels: Backend, Fix

#55 FE 통신 기능 구현
  Front/package-lock.json
  Front/package.json
  Front/src/UI/BaseButton.vue
  Front/src/components/ImageData.vue
  Front/src/components/ImageModal.vue
  Front/src/components/LogModal.vue
  Front/src/layout/TheHeader.vue
  Front/src/main.js
  Front/src/pages/bookmark.vue
  Front/src/pages/log.vue
  Front/src/pages/login.vue
  Front/src/pages/main.vue
  Front/src/pages/result.vue
  Front/src/pages/signup.vue
  Front/src/router/index.js
  Front/src/store/images.js
  Front/src/store/index.js
  Front/src/store/logs.js
  Front/src/store/results.js
  Front/src/store/socket.js
  Front/src/store/text.js
  Front/src/store/user.js
  package-lock.json
  package.json
Labels: Frontend, Feat

#59 Fix: BE 검색 기록 상세 조회 시 isBookmarked==True 일 경우 bookmarkId 를 같이 응답으로 보냄
  Back/app/controllers/searchHistory.controller.js
Labels: Backend, Fix

#60 fix: 로그 상세보기에서 북마크 삭제 기능 수정
  Front/src/components/LogModal.vue
  Front/src/pages/log.vue
Labels: Frontend, Fix

#61 FE 로그인 헤더, 결과 페이지 이미지 결과 수정
  Front/src/layout/TheHeader.vue
  Front/src/pages/main.vue
  Front/src/pages/result.vue
  Front/src/store/results.js
Labels: Frontend, Fix

#63 FE 검색 기록 페이지, 북마크 페이지 페이지 기능 구현
  Front/src/pages/bookmark.vue
  Front/src/pages/log.vue
  Front/src/store/images.js
  Front/src/store/logs.js
Labels: Frontend, Feat

#65 fix: 북마크 버튼을 모달에서만 누를 수 있게 수정
  Front/src/components/ImageData.vue
  Front/src/components/ImageModal.vue
  Front/src/pages/bookmark.vue
  Front/src/store/images.js
  Front/src/store/logs.js
Labels: Frontend, Fix

#66 FE 이미지 업로드 시 결과 업로드 화면 아래에 보여주도록 수정
  Front/src/pages/main.vue
Labels: Frontend, Fix

#67 FE 새로고침시 1페이지로 무조건 돌아가는 현상 수정
  Front/src/layout/TheHeader.vue
  Front/src/pages/bookmark.vue
  Front/src/pages/log.vue
  Front/src/store/images.js
  Front/src/store/logs.js
Labels: Frontend, Fix

#69 FEAT: BE, AI 통합
  Back/app/controllers/socketio.controller.js
  Back/app/python/__pycache__/clip.cpython-311.pyc
  Back/app/python/__pycache__/model.cpython-311.pyc
  Back/app/python/__pycache__/simple_tokenizer.cpython-311.pyc
  Back/app/python/bpe_simple_vocab_16e6.txt.gz
  Back/app/python/clip.py
  Back/app/python/inf.py
  Back/app/python/model.py
  Back/app/python/simple_tokenizer.py
  Back/app/python/test.py
  Back/app/python/train.py
Labels: Backend, Feat

#71 feat: 로딩 스피너 추가
  Front/src/components/LoadingSpinner.vue
  Front/src/pages/main.vue
Labels: Frontend, Feat

#73 Feat: png 파일 입력 시 소켓 연결 끊김 해결
  Back/config/express_config.js
Labels: Backend, Fix
